//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceMaster
    {
        public InvoiceMaster()
        {
            this.InvoiceLineMasters = new HashSet<InvoiceLineMaster>();
            this.Payment = new HashSet<Payment>();
        }
    
        public int InvoiceId { get; set; }
        public int InvoiceNr { get; set; }
        public int PartyId { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public decimal Amount { get; set; }
        public decimal VatAmount { get; set; }
        public bool IsVat { get; set; }
        public decimal TotalAmount { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual PartyMaster PartyMaster { get; set; }
        public virtual UsersMaster UsersMaster { get; set; }
        public virtual ICollection<InvoiceLineMaster> InvoiceLineMasters { get; set; }
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
