//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMaster
    {
        public ItemMaster()
        {
            this.InvoiceLineMasters = new HashSet<InvoiceLineMaster>();
            this.StockItemMasters = new HashSet<StockItemMaster>();
            this.PurchaseItemMasters = new HashSet<PurchaseItemMaster>();
        }
    
        public int ItemId { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public int UnitId { get; set; }
    
        public virtual UnitMaster UnitMaster { get; set; }
        public virtual ICollection<InvoiceLineMaster> InvoiceLineMasters { get; set; }
        public virtual ICollection<StockItemMaster> StockItemMasters { get; set; }
        public virtual ICollection<PurchaseItemMaster> PurchaseItemMasters { get; set; }
    }
}
