//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyMaster
    {
        public PartyMaster()
        {
            this.InvoiceMasters = new HashSet<InvoiceMaster>();
            this.Payment = new HashSet<Payment>();
            this.StockMaster = new HashSet<StockMaster>();
        }
    
        public int PartyId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual UsersMaster UsersMaster { get; set; }
        public virtual ICollection<InvoiceMaster> InvoiceMasters { get; set; }
        public virtual ICollection<Payment> Payment { get; set; }
        public virtual ICollection<StockMaster> StockMaster { get; set; }
    }
}
