//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseMaster
    {
        public PurchaseMaster()
        {
            this.PurchaseItemMasters = new HashSet<PurchaseItemMaster>();
            this.Purchasepays = new HashSet<Purchasepay>();
        }
    
        public int PurchaseId { get; set; }
        public int VendorId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public decimal Amount { get; set; }
        public int PurchaseNr { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual ICollection<PurchaseItemMaster> PurchaseItemMasters { get; set; }
        public virtual UsersMaster UsersMaster { get; set; }
        public virtual VendorMaster VendorMaster { get; set; }
        public virtual ICollection<Purchasepay> Purchasepays { get; set; }
    }
}
