//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMaster
    {
        public StockMaster()
        {
            this.Payment = new HashSet<Payment>();
            this.StockItemMasters = new HashSet<StockItemMaster>();
        }
    
        public int StockId { get; set; }
        public int PartyId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public decimal Amount { get; set; }
        public string InvoiceNr { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual PartyMaster PartyMaster { get; set; }
        public virtual ICollection<Payment> Payment { get; set; }
        public virtual UsersMaster UsersMaster { get; set; }
        public virtual ICollection<StockItemMaster> StockItemMasters { get; set; }
    }
}
