//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersMaster
    {
        public UsersMaster()
        {
            this.PartyMasters = new HashSet<PartyMaster>();
            this.InvoiceMasters = new HashSet<InvoiceMaster>();
            this.StockMaster = new HashSet<StockMaster>();
            this.Payments = new HashSet<Payment>();
            this.VendorMasters = new HashSet<VendorMaster>();
            this.PurchaseMasters = new HashSet<PurchaseMaster>();
            this.Purchasepays = new HashSet<Purchasepay>();
        }
    
        public int UserId { get; set; }
        public int BranchId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public bool IsSuperAdmin { get; set; }
    
        public virtual BranchMaster BranchMaster { get; set; }
        public virtual ICollection<PartyMaster> PartyMasters { get; set; }
        public virtual ICollection<InvoiceMaster> InvoiceMasters { get; set; }
        public virtual ICollection<StockMaster> StockMaster { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<VendorMaster> VendorMasters { get; set; }
        public virtual ICollection<PurchaseMaster> PurchaseMasters { get; set; }
        public virtual ICollection<Purchasepay> Purchasepays { get; set; }
    }
}
